### ISSUE TITLE
$(call inherit-product-if-exists, hardware/qcom/msm8994/msm8992.mk) $(call inherit-product-if-exists, vendor/qcom/gpu/msm8994/msm8994-gpu-vendor.mk) $(call inherit-product-if-exists, vendor/andropax/extras.mk)

### ISSUE THREAD

**Issue by Aromer-room** [AndropaX/android_device_xiaomi_libra#3]
$(call inherit-product-if-exists, hardware/qcom/msm8994/msm8992.mk)
$(call inherit-product-if-exists, vendor/qcom/gpu/msm8994/msm8994-gpu-vendor.mk)
$(call inherit-product-if-exists, vendor/andropax/extras.mk)
在哪里可以下载

**Comment by Aromer-room** [comment]
十分感谢
(call inherit-product-if-exists, vendor/andropax/extras.mk)
$(call inherit-product-if-exists, vendor/qcom/gpu/msm8994/msm8994-gpu-vendor.mk)
剩余这俩在哪里可以找到？谢谢

**Comment by AndropaX** [comment]
Nowhere

**Comment by AndropaX** [comment]
PS: please write in english

**Comment by Aromer-room** [comment]
Thank you very much.
These two do not download configuration to the device?
(call inherit-product-if-exists, vendor/andropax/extras.mk)
$(call inherit-product-if-exists, vendor/qcom/gpu/msm8994/msm8994-gpu-vendor.mk)

**Comment by Aromer-room** [comment]
My English is not very good, very sorry

**Comment by AndropaX** [comment]
No, it's nothing important.

**Comment by Aromer-room** [comment]
Thank you very much.
